#!/bin/bash

if [ $# -ne 5 ]; then
	echo "El numero de parametros es incorrecto."
	echo "USO: $0 <usuario> <UID> <GID> <comentario> <shell_usuario>"
	exit 1
fi

if [ $(cat passwd | cut -d: -f1 | grep -c "$1") -gt 0 ]; then
	echo "El usuario ya existe."
	exit 1
fi

if [ $(cat passwd | cut -d: -f3 | grep -c "$2") -gt 0 ]; then
	echo "El UID debe de ser unico."
	exit 1
fi

if [ $(getent group | cut -d: -f3 | grep -c "$3") -eq 0 ]; then
	echo "El GID debe existir."
	exit 1
fi

echo "$1:x:$2:$3:$4:/home/$1:$5" >> passwd
exit 0 # useless
