#!/bin/bash
if [ $# -ne 1 ]; then
	echo "El numero de parametros es incorrecto."
	echo "USO: $0 <usuario>"
	exit 1
fi

if ! ./ExisteUsuario $1 >/dev/null; then
	echo "El usuario $1 no existe."
	exit 1
fi

ps uawx | grep "^$1 .*$"
